# Generated by Django 2.2.16 on 2020-09-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='name',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
